#!/usr/bin/python3
import sys


def factorize():
    with open(sys.argv[1], 'r') as data:
    	 for line in data:
	     num = int(line.strip())
	     for div in range(2, num // 2):
	     	 if num % div == 0:
		    p = num / div
		    print("{}={}*{}".format(num, int(p), div))
		    break

factorize()
